"""change shares columns to float for fractional shares

Revision ID: 7fb2f23ae2dd
Revises: 85b1c516e14f
Create Date: 2025-12-10 22:27:17.449689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fb2f23ae2dd'
down_revision: Union[str, Sequence[str], None] = '85b1c516e14f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_issuances_recipient'), table_name='token_issuances')
    op.drop_index(op.f('ix_token_issuances_token_id'), table_name='token_issuances')
    op.drop_table('token_issuances')
    op.alter_column('funding_rounds', 'shares_issued',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('investments', 'shares_received',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('vesting_schedules', 'interval',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'minute'::character varying"))
    op.alter_column('vesting_schedules', 'intervals_released',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vesting_schedules', 'intervals_released',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('vesting_schedules', 'interval',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'minute'::character varying"))
    op.alter_column('investments', 'shares_received',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('funding_rounds', 'shares_issued',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_table('token_issuances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipient', sa.VARCHAR(length=44), autoincrement=False, nullable=False),
    sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('issued_by', sa.VARCHAR(length=44), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tx_signature', sa.VARCHAR(length=88), autoincrement=False, nullable=True),
    sa.Column('slot', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.token_id'], name=op.f('token_issuances_token_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('token_issuances_pkey'))
    )
    op.create_index(op.f('ix_token_issuances_token_id'), 'token_issuances', ['token_id'], unique=False)
    op.create_index(op.f('ix_token_issuances_recipient'), 'token_issuances', ['recipient'], unique=False)
    # ### end Alembic commands ###
