"""change price_per_share columns to float for precision

Revision ID: f81c49d664de
Revises: 7fb2f23ae2dd
Create Date: 2025-12-10 22:37:18.593658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f81c49d664de'
down_revision: Union[str, Sequence[str], None] = '7fb2f23ae2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: token_issuances table already dropped in previous migration
    op.alter_column('funding_rounds', 'price_per_share',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('investments', 'price_per_share',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('share_grants', 'price_per_share',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('share_positions', 'price_per_share',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('valuation_events', 'price_per_share',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valuation_events', 'price_per_share',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('share_positions', 'price_per_share',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('share_grants', 'price_per_share',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('investments', 'price_per_share',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('funding_rounds', 'price_per_share',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # Note: token_issuances table recreation removed - handled by previous migration
    # ### end Alembic commands ###
